# Generated by Django 5.1.7 on 2025-03-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания отправки'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='sent_messages',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(blank=True, choices=[('created', 'Создана'), ('started', 'Запущена'), ('completed', 'Завершена')], default='created', max_length=10, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='successful_attempts',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='unsuccessful_attempts',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
